image: docker:latest
services:
- docker:dind

stages:
- test

test-client:
  stage: test
  script:
    - docker pull registry.gitlab.com/raiyanyahya/docker-python-version
    - docker run python test.py here