stages:
  - build
  - testmyimage

build:
  image: registry.gitlab.com/raiyanyahya/docker-python-version
  stage: build
  script:
    - python --version

testmyimage:
  image: registry.gitlab.com/raiyanyahya/docker-python-version
  stage: testmyimage
  script:
    - testinput